export const FORTUNES = [
  "Your patience today will bring unexpected rewards tomorrow.",
  "A kind word now opens doors that once seemed closed.",
  "The seeds you plant with diligence will bloom in their own season.",
  "Trust the path that winds — it often leads to the finest views.",
  "Small acts of courage accumulate into great adventures.",
  "A helping hand offered freely returns tenfold.",
  "Your curiosity is a compass pointing toward your purpose.",
  "The quiet mind hears what the busy mind misses.",
  "Persistence dissolves obstacles the way water shapes stone.",
  "An open heart invites the world to surprise you.",
  "Today's stumble is tomorrow's stride.",
  "The light you carry inside you is brighter than you believe.",
  "New beginnings are disguised as ordinary mornings.",
  "Generosity given without expectation always finds its way back.",
  "Your greatest strength lies just beyond your comfort zone.",
  "The universe conspires in favor of those who dare to dream.",
  "A smile shared with a stranger plants joy in unexpected soil.",
  "Clarity arrives when you stop chasing and start listening.",
  "Every setback is an invitation to grow wiser.",
  "The best chapters of your story are still unwritten.",
  "What you water with attention will flourish.",
  "Embrace the unknown — it is where possibility lives.",
  "Your effort today is the foundation of tomorrow's ease.",
  "Wisdom speaks softly; be still enough to hear it.",
  "The one who asks questions walks through doors others never find.",
  "Kindness is a currency that never loses its value.",
  "Fortune favors the thoughtful as much as the bold.",
  "An idea nurtured in silence can change the world.",
  "The joy you seek has been beside you all along.",
  "Even the longest journey begins with a single, confident step.",
  "Your instincts have been honed by every experience you have faced.",
  "Laughter is the shortest distance between two people.",
  "A problem shared is a problem halved; a joy shared is doubled.",
  "The door you hesitate before is often the most important one.",
  "Resilience is the quiet art of returning to yourself.",
  "Today holds more possibility than yesterday's fears suggested.",
  "Beauty is found in the details that patience reveals.",
  "Your next great idea is closer than you think.",
  "Courage is not the absence of fear but the decision to move anyway.",
  "The universe rewards those who show up fully.",
  "Every ending clears space for a richer beginning.",
  "Your words today have the power to lift someone's spirit.",
  "The treasure you seek lies within the work you are willing to do.",
  "Adaptability is the quiet superpower of the wise.",
  "Gratitude turns what you have into enough.",
  "A creative mind finds solutions where others see only walls.",
  "The moment you decide is the moment things begin to change.",
  "Peace is not found in circumstances but in perspective.",
  "Your story matters more than you will ever fully know.",
  "The stars have always been on your side.",
  "Discipline practiced daily becomes freedom over time.",
  "Each challenge you overcome expands what you believe is possible.",
  "The ripple of one good deed travels farther than you imagine.",
  "Your unique perspective is a gift the world needs.",
  "Timing and tenacity together create extraordinary outcomes.",
  "The answer you need will arrive when your mind is clear.",
  "Boldness and preparation together make an unstoppable pair.",
  "You are closer to a breakthrough than you realize.",
  "A well-placed pause is worth a thousand rushed words.",
  "The courage to begin is already inside you.",
  "Every dawn is a fresh ledger for a new kind of success.",
  "Shared laughter binds hearts more firmly than shared hardship.",
  "The most rewarding paths rarely come with detailed maps.",
  "Your commitment to growth inspires those around you silently.",
  "In stillness, the answers you seek rise to the surface.",
  "The energy you invest in others multiplies and returns.",
  "Every question you ask brings you one step closer to mastery.",
  "A moment of reflection today saves hours of regret tomorrow.",
  "Your warmth is a gift that costs nothing and means everything.",
  "The world opens itself to those who remain genuinely curious.",
  "Obstacles are merely raw materials for remarkable stories.",
  "Trust is built in small moments and treasured for a lifetime.",
  "The person who persists with grace will outlast any storm.",
  "Your intuition is a well-tuned instrument — listen to it.",
  "New connections made today may become lifelong sources of strength.",
  "What seems impossible today will feel ordinary once you achieve it.",
  "The habits you form now are sculpting the life you will live.",
  "Every act of honesty strengthens the foundation of your relationships.",
  "Clarity of purpose turns hard work into meaningful effort.",
  "The quiet confidence you carry speaks louder than words.",
  "Risk taken with preparation is simply opportunity in disguise.",
  "Your ability to adapt is your greatest competitive advantage.",
  "A day spent in service to others is never wasted.",
  "The next milestone you reach will open two more on the horizon.",
  "Learning from failure is how champions are quietly made.",
  "The universe has a way of rewarding consistent integrity.",
  "Your creativity is an infinite resource — draw from it freely.",
  "Every moment of genuine presence is an investment in joy.",
  "The lessons hardest learned become the ones most deeply valued.",
  "Your resolve in difficult times defines the character you carry forward.",
  "Small consistencies performed over time yield remarkable results.",
  "The light at the end of the tunnel is real — keep moving.",
  "Asking for help is not weakness; it is wisdom in action.",
  "Your potential is not a fixed quantity — it grows with use.",
  "The relationships you nurture now will sustain you through all seasons.",
  "Every moment of gratitude adds a brick to a life well built.",
  "The future belongs to those who prepare for it with joy.",
  "Your next chapter begins the moment you turn this page.",
  "Fortune smiles on those who greet it with an open hand.",
  "The best is yet to come — keep your eyes and heart open.",
] as const

/** Pick a random fortune index that is different from `currentIndex`. */
export function pickFortuneIndex(currentIndex: number | null): number {
  const total = FORTUNES.length
  let next: number
  do {
    next = Math.floor(Math.random() * total)
  } while (next === currentIndex)
  return next
}
